---
platform: linux
image: docker:///dingotiles/dingo-docs-pipeline

inputs:
- name: docs-ci
- name: docs

outputs:
- name: docs-app

params:
  app_name:
  app_hosts:

run:
  path: docs-ci/ci/tasks/build-docs-app.sh
