---
book_repo: dingodb/docs-book
cred_repo: dingodb/docs-site-credentials
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: false
feedback_enabled: false

sections:
- repository:
    name: dingodb/docs-dingo-s3
  directory: dingo-s3
  subnav_template: dingo_s3_subnav.erb


template_variables:
  book_title: Dingo Tiles Documentation
  book_title_short: Dingo Docs

  company: Dingo Tiles
  support_url: https://slack.dingotiles.com

  domain_name: localhost

  product_link:
  # support_link: <a href="http://slack.dingotiles.com" target="_blank">Chat with us on Slack</a>
  support_link: <script async defer src="http://slack.dingotiles.com/slackin.js"></script>
  support_call_to_action: <script async defer src="http://slack.dingotiles.com/slackin.js"></script>
  hero_text: configyml.hero_text

  # https://cse.google.com/cse/
  cse_id: configyml.cse_id
  ga_account_id: configyml.ga_account_id

public_host: localhost:4567
