---
groups:
- name: deploy
  jobs:
  - deploy-prod
  - deploy-postgresql
- name: ci
  jobs:
  - build-task-image

jobs:
- name: deploy-prod
  public: false
  serial: true
  plan:
  - {get: docs-ci}
  - {get: docs, resource: docs-prod, trigger: true}
  - task: build-docs-app
    file: docs-ci/ci/tasks/build-docs-app.yml
    config:
      params:
        app_name: docs
        app_hosts: "[www,docs]"
  - put: docs-web-app
    params:
      manifest: docs-app/docs-book/final_app/manifest.yml
      path: docs-app/docs-book/final_app
      current_app_name: docs

- name: deploy-postgresql
  public: false
  serial: true
  plan:
  - {get: docs-ci}
  - {get: docs, resource: docs-postgresql, trigger: true}
  - task: build-docs-app
    file: docs-ci/ci/tasks/build-docs-app.yml
    config:
      params:
        app_name: docs-postgresql
        app_hosts: "[alpha,pg,postgresql]"
  - put: docs-web-app
    params:
      manifest: docs-app/docs-book/final_app/manifest.yml
      path: docs-app/docs-book/final_app
      current_app_name: docs-postgresql

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: docs-docker-image
    trigger: true
  - put: docker-image
    params:
      build: docs-docker-image/ci/ci_image

resources:
- name: docs-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: master
    private_key: {{github-key}}
- name: docs-prod
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: master
    private_key: {{github-key}}
    paths:
      - docs-book/**/*
      - docs-layout-repo/**/*
      - docs-dingo-s3/*
- name: docs-postgresql
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: postgresql
    private_key: {{github-key}}
    paths:
      - docs-book/**/*
      - docs-layout-repo/**/*
      - docs-dingo-s3/*

- name: docs-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    skip_cert_check: false
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}


- name: docs-docker-image
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: master
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-docs-pipeline
