---
groups:
- name: deploy
  jobs:
  - deploy
- name: image
  jobs:
  - build-task-image

jobs:
- name: deploy
  public: false
  serial: true
  plan:
  - get: docs
  - {get: docs-contents, trigger: true}
  - task: docs-app
    file: docs/ci/tasks/build-docs-app.yml
  - put: docs-web-app
    params:
      manifest: docs-app/docs/docs-book/final_app/manifest.yml
      path: docs-app/docs/docs-book/final_app
      current_app_name: docs

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: docs-docker-image
    trigger: true
  - put: docker-image
    params:
      build: docs-docker-image/ci/ci_image

resources:
- name: docs
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: {{docs-branch}}
    private_key: {{github-key}}
- name: docs-contents
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: {{docs-branch}}
    private_key: {{github-key}}
    paths: [docs*/**/*]

- name: docs-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    skip_cert_check: false
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}


- name: docs-docker-image
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: {{docs-branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingodb/dingo-docs-pipeline
