---
groups:
- name: deploy
  jobs:
  - deploy
- name: image
  jobs:
  - build-task-image

jobs:
- name: deploy
  public: true
  serial: true
  plan:
  - get: docs
  - task: build-docs-app
    file: docs/ci/tasks/build-docs-app.yml

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: docs-docker-image
    trigger: true
  - put: docker-image
    params:
      build: docs-docker-image/ci/ci_image

resources:
- name: docs
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
- name: docs-docker-image
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-docs.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingodb/dingo-docs-pipeline
